### ISSUE TITLE
light backup后，查看备份软件列表，显示不正确

### ISSUE THREAD

**Issue by ziguayungui** [6ang996/istore-dev#1]
![68d9c188079638c13ac5a2890ebcffa](https://user-images.githubusercontent.com/7206387/144004483-76175ccd-2817-4e8b-882a-8e5bf11e12c4.png)
![e63c401838aad8076f5633963b1177e](https://user-images.githubusercontent.com/7206387/144004504-91c8357a-fff1-4f2b-b788-bbd2c7348d86.png)

**Comment by 6ang996** [comment]
fixed [https://github.com/6ang996/istore/commit/3b7a04eb2cf5cc7e30f7b35a345ec84be5ecee48](url)

**Comment by 6ang996** [comment]
fixd https://github.com/6ang996/istore/commit/c71f221b75ac7b49defa608340feacfa7d197cbf
